---
title: "homework_3"
author: "annalatoff"
date: "11/2/2019"
output: html_document
---

Anna, this is a Rmarkdown file which is desgined to produce a literate program by integrating R code with 
Markdown. But its actually not really set up that way and doesnt work properly.  It looks like youve probably included straight R code into markdown sections. We'll actually cover how to make files like this that work 
in class but havent yet.  I've put some comments here for the purpose of criticuing the R script, but I've also uploaded a demo document to your repository. 

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE) # not necessary. 
```

#this assignment uses R version 3.6.1#
#A Latoff 10.31.19#
#take home assignment 3#  JY: suggest a preamble more like the one in demo

#installing ggplot2#
install.packages("ggplot2") # DONT KEEP THESE LINES IN FILE THEY CAUSE PROBLEMS
library(ggplot2) 
data("diamonds") # DONT NEED THE DOUBLE QUOTES

#visualizing data#
head(diamonds, 6) # YES though dont need six as head() defaults to this number anyway


# you do not need to print the results in your script your self (nor should you). It will cause problems when you # want to run it

# A tibble: 6 x 10
  carat cut       color clarity depth table price     x     y     z
  <dbl> <ord>     <ord> <ord>   <dbl> <dbl> <int> <dbl> <dbl> <dbl>
1 0.23  Ideal     E     SI2      61.5    55   326  3.95  3.98  2.43
2 0.21  Premium   E     SI1      59.8    61   326  3.89  3.84  2.31
3 0.23  Good      E     VS1      56.9    65   327  4.05  4.07  2.31
4 0.290 Premium   I     VS2      62.4    58   334  4.2   4.23  2.63
5 0.31  Good      J     SI2      63.3    58   335  4.34  4.35  2.75
6 0.24  Very Good J     VVS2     62.8    57   336  3.94  3.96  2.48


## FOR GRADE The assignement was 2 days late, thus -10 points while the script contains the correct R commands
## it doesnt run as an R script, nor does it correctly compile as an R markdown notebook or dynamic document. So ## I have to take a few points there ultimately it is  75/100 